config/routes.rb
Rails.application.routes.draw do

  root 'courses#index'

  get 'greeter/hello' => "greeter#hello"
  get 'greeter/goodbye' => "greeter#goodbye"

end

app/models/coursera.rb
class Coursera
	include HTTParty

	base_uri 'https://api.coursera.org/api/catalog.v1/courses'
	default_params fields: "smallIcon,shortDescription", q: "search"
	format :json

	def self.for term
		get("", query: {query: term}) ["elements"]
	end
end

# pp Coursera.for "python"

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  	@search_term = params[:looking_for] || 'python'
  	@courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
  	random_names = ["Adam", "George", "Sam"]
  	@name = random_names.sample
  	@time = Time.now
  	@times_displayed ||= 0
  	@times_displayed += 1
  end
  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
	def formatted_time(time)
		time.strftime("%d-%b-%Y %I:%M%p IST - %s")
	end
end

app/views/courses/index.html.erb
<h1>Searching for - <%= @search_term %></h1>

<% if @courses.nil? %>

	<p>No courses found with relevant info... Sorry</p>

<% else %>

	<table border='1'>

		<thead>
			<tr>
				<th>Image</th>
				<th>Name</th>
				<th>Description</th>
			</tr>
		</thead>

		<tbody>
			<% @courses.each do |course| %>
				<tr class=<%= cycle('even', 'odd') %>>
					<td><%= image_tag(course["smallIcon"]) %></td>
					<td><%= course["name"] %></td>
					<td><%= course["shortDescription"] %></td>
				</tr>
			<% end %>
		</tbody>

	</table>

<% end %>

<p style="color: #9c1628"><b>Note:</b> Use the parameter <i>looking_for</i> to change the search parameter. Example: <span style="font-family: monospace">https://coursera-rails.herokuapp.com/?looking_for=ruby</span></p>
<p>An app by <b>Shubham Gupta</b></p>

app/views/greeter/hello.html.erb
<% random_names = ["Adam", "George", "Sam"] %>
<h1> Greetings, <%= @name %></h1>
<p>The time now is <%= formatted_time(@time) %></p>
<p>This page has been viewed <%= @times_displayed %> times.</p>

<p><%= link_to "Google", "https://www.google.com" %></p>
<p><%= link_to "Goodbye", greeter_goodbye_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseraRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>